[tool.poetry]
name = "score-sde"
version = "1.0.1a1"
description = ""
authors = ["Michael Hutchinson <michael.hutchinson@stats.ox.ac.uk>", "Emile Mathieu <>"]
readme = "README.md"

packages = [
    { include = "riemannian_score_sde" },
]

[tool.poetry.dependencies]
python = "^3.10"
tqdm = "^4.0"
seaborn = "^0.10"
scipy = "^1.5"
wandb = "^0.10"
hydra-core = "1.3.2"
hydra-colorlog = "1.2.0"
hydra-joblib-launcher = "1.2.0"
submitit = { git = "https://github.com/emilemathieu/submitit.git" }
geomstats = { git = "https://github.com/oxcsml/geomstats.git" }
pyrecest = { git = "https://github.com/FlorianPfaff/pyRecEst.git"}
hydra-submitit-launcher = { git = "https://github.com/emilemathieu/hydra.git", subdirectory = "plugins/hydra_submitit_launcher" }
jax = "0.4.26"
jaxlib = "0.4.26"
dm-haiku = "*"
optax = "0.2.2"
distrax = "*"
diffrax = "*"
fsspec = { version = ">=2021.05.0, !=2021.06.0", extras = ["http"] }
joblib = "*"
autograd = "*"
protobuf = "^3.20.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

